# Generated by Django 3.0.14 on 2021-04-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_accounts', '0003_alter_ip_address'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='transfer',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, to='oscar_accounts.Transfer'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tooltype',
            name='type',
            field=models.CharField(blank='True', max_length=256),
        ),
    ]
