# Generated by Django 3.0.14 on 2021-04-28 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_accounts', '0003_alter_ip_address'),
        ('tools', '0002_auto_20210428_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oscar_accounts.Transfer'),
        ),
    ]
