# Generated by Django 3.0.14 on 2021-04-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20210428_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltype',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='tooltype',
            name='type',
            field=models.CharField(blank='True', max_length=256, null='True'),
        ),
    ]
