# Generated by Django 3.0.14 on 2021-04-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20210428_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltype',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
