# Generated by Django 3.0.14 on 2021-04-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20210428_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltype',
            name='value',
            field=models.IntegerField(),
        ),
    ]
