# Generated by Django 3.0.14 on 2021-05-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20210509_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tooltype',
            name='type',
            field=models.CharField(default='-', max_length=256),
        ),
    ]
